[phases.setup]
nixPkgs = ['...', 'php82Extensions.gd', 'php82Extensions.redis', 'php82Extensions.pdo_mysql', 'php82Extensions.sodium']

[phases.install]
cmds = ['composer install --optimize-autoloader --no-dev']